# Generated by Django 5.0.14 on 2025-11-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("virtuallibrary", "0019_remove_userprofile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_aluno", models.CharField(max_length=100)),
                (
                    "cpf_aluno",
                    models.CharField(default="000.000.000-00", max_length=14),
                ),
                ("data_emprestimo", models.DateTimeField(auto_now_add=True)),
                ("data_devolucao", models.DateField(blank=True, null=True)),
                ("devolvido", models.BooleanField(default=False)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimos_api",
                        to="virtuallibrary.book",
                    ),
                ),
            ],
        ),
    ]
