# Generated by Django 5.0.14 on 2025-09-10 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publish']},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-publish'], name='virtuallibr_publish_7c7a97_idx'),
        ),
    ]
