# Generated by Django 5.0.14 on 2025-09-13 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('virtuallibrary', '0005_book_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publish']},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-publish'], name='virtuallibr_publish_7c7a97_idx'),
        ),
    ]
