# Generated by Django 5.0.14 on 2025-09-16 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0007_book_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='posted_by',
            field=models.ForeignKey(default=1, help_text='Admin que adicionou este livro ao sistema', on_delete=django.db.models.deletion.CASCADE, related_name='books_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2024-01-01', help_text='Data original de publicação do livro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Autor Desconhecido', help_text='Nome do autor do livro', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
