# Generated by Django 5.0.14 on 2025-09-16 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0008_book_posted_by_book_publication_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perfil', models.CharField(choices=[('estudante', 'Estudante'), ('bibliotecario', 'Bibliotecário'), ('professor', 'Professor')], default='estudante', max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20)),
                ('curso', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
