# Generated by Django 5.0.14 on 2025-09-16 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0010_emprestimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emprestimo',
            unique_together={('user', 'book')},
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
    ]
