# Generated by Django 5.0.14 on 2025-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0011_alter_emprestimo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primeiro_nome',
            field=models.CharField(blank=True, help_text='Nome adicional do perfil', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ultimo_nome',
            field=models.CharField(blank=True, help_text='Sobrenome adicional do perfil', max_length=50),
        ),
    ]
