# Generated by Django 5.0.14 on 2025-09-17 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0012_alter_userprofile_options_userprofile_primeiro_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_emprestimo']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='posted_by',
            field=models.ForeignKey(help_text='Admin que adicionou este livro ao sistema', on_delete=django.db.models.deletion.CASCADE, related_name='books_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Data original de publicação do livro', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
