# Generated by Django 5.0.14 on 2025-09-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0013_alter_emprestimo_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
