# Generated by Django 5.0.14 on 2025-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0016_remove_userprofile_bio_userprofile_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='matricula',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
