# Generated by Django 5.0.14 on 2025-09-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0017_remove_userprofile_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='curso',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
