# Generated by Django 5.0.14 on 2025-09-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0018_userprofile_curso_userprofile_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
