# Generated by Django 5.0.14 on 2025-11-26 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtuallibrary', '0019_remove_userprofile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emprestimo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('EM', 'Emprestado'), ('DV', 'Devolvido')], default='EM', max_length=2),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='virtuallibrary.book'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['status'], name='virtuallibr_status_0e8553_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['data_emprestimo'], name='virtuallibr_data_em_532053_idx'),
        ),
    ]
